language: node_js
node_js:
  - 8.11.3
jobs:
  include:
    - stage: "lint"
    - script: "npm run lint" 
    - stage: "test"
    - script: "npm run test"
    - stage: deploy
    - script: "echo app deployed..  "
branches:
  only:
  - master
  - development